package jp.go.meti.drone.user_attr.repository;

import java.util.List;
import jp.go.meti.drone.user_attr.repository.entity.OperatorAttributeEntity;
import jp.go.meti.drone.user_attr.repository.entity.OperatorAttributeEntityExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface OperatorAttributeRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    long countByExample(OperatorAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    int deleteByExample(OperatorAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    int deleteByPrimaryKey(String operatorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    int insert(OperatorAttributeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    int insertSelective(OperatorAttributeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    List<OperatorAttributeEntity> selectByExampleWithRowbounds(OperatorAttributeEntityExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    List<OperatorAttributeEntity> selectByExample(OperatorAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    OperatorAttributeEntity selectByPrimaryKey(String operatorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    int updateByExampleSelective(@Param("row") OperatorAttributeEntity row, @Param("example") OperatorAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    int updateByExample(@Param("row") OperatorAttributeEntity row, @Param("example") OperatorAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    int updateByPrimaryKeySelective(OperatorAttributeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    int updateByPrimaryKey(OperatorAttributeEntity row);
}