package jp.go.meti.drone.user_attr.repository;

import java.time.LocalDateTime;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import jp.go.meti.drone.user_attr.repository.entity.UserAttributeEntity;
import jp.go.meti.drone.user_attr.repository.entity.UserAttributeEntityExample;
import jp.go.meti.drone.user_attr.repository.entity.UserOperatorAttributeEntity;

@Mapper
public interface UserAttributeRepository {

    /**
     * 事業者/ユーザ属性全検索
     * 
     * @return 事業者/ユーザ属性リスト
     */
    List<UserOperatorAttributeEntity> selectAllUnion(@Param("deleted") Boolean deleted);

    /**
     * 指定日時以降の事業者/ユーザ属性検索
     * 
     * @param start 開始日時（更新日時）
     * @param deleted 削除済み：true
     * @return 事業者/ユーザ属性リスト
     */
    List<UserOperatorAttributeEntity> selectByUpdateDatetimeUnion(@Param("startTimestamp") LocalDateTime start,
        @Param("deleted") Boolean deleted);

    /**
     * 該当するUUIDの事業者/ユーザ属性検索
     * 
     * @param operatorIds UUID(事業者テーブル：operator_id、ユーザテーブル：user_id)
     * @param deleted 削除済み：true
     * @return 事業者/ユーザ属性リスト
     */
    List<UserOperatorAttributeEntity> selectByOperatorIdUnion(@Param("operatorIds") List<String> operatorIds,
        @Param("deleted") Boolean deleted);

    /**
     * 該当するメールアドレスの事業者/ユーザ属性検索
     * 
     * @param mailAddresses メールアドレス
     * @param deleted 削除済み：true
     * @return 事業者/ユーザ属性リスト
     */
    List<UserOperatorAttributeEntity> selectByMailAddressUnion(@Param("mailAddresses") List<String> mailAddresses,
        @Param("deleted") Boolean deleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    long countByExample(UserAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    int deleteByExample(UserAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    int insert(UserAttributeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    int insertSelective(UserAttributeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    List<UserAttributeEntity> selectByExampleWithRowbounds(UserAttributeEntityExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    List<UserAttributeEntity> selectByExample(UserAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    UserAttributeEntity selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    int updateByExampleSelective(@Param("row") UserAttributeEntity row, @Param("example") UserAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    int updateByExample(@Param("row") UserAttributeEntity row, @Param("example") UserAttributeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    int updateByPrimaryKeySelective(UserAttributeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    int updateByPrimaryKey(UserAttributeEntity row);
}