package jp.go.meti.drone.user_attr.repository.entity;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class OperatorAttributeEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_attribute.operator_id
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    private String operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_attribute.mail_address
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    private String mailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_attribute.operator_name
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    private String operatorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_attribute.role
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_attribute.dips_account_id
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    private String dipsAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_attribute.dips_account_name
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    private String dipsAccountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_attribute.phone_number
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_attribute.swim_operator_id
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    private String swimOperatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_attribute.creation_id
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    private String creationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_attribute.creation_datetime
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    private LocalDateTime creationDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_attribute.update_id
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_attribute.update_datetime
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    private LocalDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator_attribute.deleted_flag
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    private Boolean deletedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table operator_attribute
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    private static final long serialVersionUID = 1L;
}