package jp.go.meti.drone.user_attr.repository.entity;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class OperatorAttributeEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table operator_attribute
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table operator_attribute
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table operator_attribute
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table operator_attribute
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    protected boolean forUpdate;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    public OperatorAttributeEntityExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    public void setForUpdate(boolean forUpdate) {
        this.forUpdate = forUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator_attribute
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    public boolean isForUpdate(boolean forUpdate) {
        this.forUpdate = forUpdate;
        return forUpdate;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table operator_attribute
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOperatorIdIsNull() {
            addCriterion("operator_id is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNotNull() {
            addCriterion("operator_id is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdEqualTo(String value) {
            addCriterion("operator_id =", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotEqualTo(String value) {
            addCriterion("operator_id <>", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThan(String value) {
            addCriterion("operator_id >", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThanOrEqualTo(String value) {
            addCriterion("operator_id >=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThan(String value) {
            addCriterion("operator_id <", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThanOrEqualTo(String value) {
            addCriterion("operator_id <=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLike(String value) {
            addCriterion("operator_id like", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotLike(String value) {
            addCriterion("operator_id not like", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIn(List<String> values) {
            addCriterion("operator_id in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotIn(List<String> values) {
            addCriterion("operator_id not in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdBetween(String value1, String value2) {
            addCriterion("operator_id between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotBetween(String value1, String value2) {
            addCriterion("operator_id not between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andMailAddressIsNull() {
            addCriterion("mail_address is null");
            return (Criteria) this;
        }

        public Criteria andMailAddressIsNotNull() {
            addCriterion("mail_address is not null");
            return (Criteria) this;
        }

        public Criteria andMailAddressEqualTo(String value) {
            addCriterion("mail_address =", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressNotEqualTo(String value) {
            addCriterion("mail_address <>", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressGreaterThan(String value) {
            addCriterion("mail_address >", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressGreaterThanOrEqualTo(String value) {
            addCriterion("mail_address >=", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressLessThan(String value) {
            addCriterion("mail_address <", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressLessThanOrEqualTo(String value) {
            addCriterion("mail_address <=", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressLike(String value) {
            addCriterion("mail_address like", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressNotLike(String value) {
            addCriterion("mail_address not like", value, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressIn(List<String> values) {
            addCriterion("mail_address in", values, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressNotIn(List<String> values) {
            addCriterion("mail_address not in", values, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressBetween(String value1, String value2) {
            addCriterion("mail_address between", value1, value2, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andMailAddressNotBetween(String value1, String value2) {
            addCriterion("mail_address not between", value1, value2, "mailAddress");
            return (Criteria) this;
        }

        public Criteria andOperatorNameIsNull() {
            addCriterion("operator_name is null");
            return (Criteria) this;
        }

        public Criteria andOperatorNameIsNotNull() {
            addCriterion("operator_name is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorNameEqualTo(String value) {
            addCriterion("operator_name =", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameNotEqualTo(String value) {
            addCriterion("operator_name <>", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameGreaterThan(String value) {
            addCriterion("operator_name >", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameGreaterThanOrEqualTo(String value) {
            addCriterion("operator_name >=", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameLessThan(String value) {
            addCriterion("operator_name <", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameLessThanOrEqualTo(String value) {
            addCriterion("operator_name <=", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameLike(String value) {
            addCriterion("operator_name like", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameNotLike(String value) {
            addCriterion("operator_name not like", value, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameIn(List<String> values) {
            addCriterion("operator_name in", values, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameNotIn(List<String> values) {
            addCriterion("operator_name not in", values, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameBetween(String value1, String value2) {
            addCriterion("operator_name between", value1, value2, "operatorName");
            return (Criteria) this;
        }

        public Criteria andOperatorNameNotBetween(String value1, String value2) {
            addCriterion("operator_name not between", value1, value2, "operatorName");
            return (Criteria) this;
        }

        public Criteria andRoleIsNull() {
            addCriterion("role is null");
            return (Criteria) this;
        }

        public Criteria andRoleIsNotNull() {
            addCriterion("role is not null");
            return (Criteria) this;
        }

        public Criteria andRoleEqualTo(String value) {
            addCriterion("role =", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotEqualTo(String value) {
            addCriterion("role <>", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleGreaterThan(String value) {
            addCriterion("role >", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleGreaterThanOrEqualTo(String value) {
            addCriterion("role >=", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLessThan(String value) {
            addCriterion("role <", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLessThanOrEqualTo(String value) {
            addCriterion("role <=", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleLike(String value) {
            addCriterion("role like", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotLike(String value) {
            addCriterion("role not like", value, "role");
            return (Criteria) this;
        }

        public Criteria andRoleIn(List<String> values) {
            addCriterion("role in", values, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotIn(List<String> values) {
            addCriterion("role not in", values, "role");
            return (Criteria) this;
        }

        public Criteria andRoleBetween(String value1, String value2) {
            addCriterion("role between", value1, value2, "role");
            return (Criteria) this;
        }

        public Criteria andRoleNotBetween(String value1, String value2) {
            addCriterion("role not between", value1, value2, "role");
            return (Criteria) this;
        }

        public Criteria andDipsAccountIdIsNull() {
            addCriterion("dips_account_id is null");
            return (Criteria) this;
        }

        public Criteria andDipsAccountIdIsNotNull() {
            addCriterion("dips_account_id is not null");
            return (Criteria) this;
        }

        public Criteria andDipsAccountIdEqualTo(String value) {
            addCriterion("dips_account_id =", value, "dipsAccountId");
            return (Criteria) this;
        }

        public Criteria andDipsAccountIdNotEqualTo(String value) {
            addCriterion("dips_account_id <>", value, "dipsAccountId");
            return (Criteria) this;
        }

        public Criteria andDipsAccountIdGreaterThan(String value) {
            addCriterion("dips_account_id >", value, "dipsAccountId");
            return (Criteria) this;
        }

        public Criteria andDipsAccountIdGreaterThanOrEqualTo(String value) {
            addCriterion("dips_account_id >=", value, "dipsAccountId");
            return (Criteria) this;
        }

        public Criteria andDipsAccountIdLessThan(String value) {
            addCriterion("dips_account_id <", value, "dipsAccountId");
            return (Criteria) this;
        }

        public Criteria andDipsAccountIdLessThanOrEqualTo(String value) {
            addCriterion("dips_account_id <=", value, "dipsAccountId");
            return (Criteria) this;
        }

        public Criteria andDipsAccountIdLike(String value) {
            addCriterion("dips_account_id like", value, "dipsAccountId");
            return (Criteria) this;
        }

        public Criteria andDipsAccountIdNotLike(String value) {
            addCriterion("dips_account_id not like", value, "dipsAccountId");
            return (Criteria) this;
        }

        public Criteria andDipsAccountIdIn(List<String> values) {
            addCriterion("dips_account_id in", values, "dipsAccountId");
            return (Criteria) this;
        }

        public Criteria andDipsAccountIdNotIn(List<String> values) {
            addCriterion("dips_account_id not in", values, "dipsAccountId");
            return (Criteria) this;
        }

        public Criteria andDipsAccountIdBetween(String value1, String value2) {
            addCriterion("dips_account_id between", value1, value2, "dipsAccountId");
            return (Criteria) this;
        }

        public Criteria andDipsAccountIdNotBetween(String value1, String value2) {
            addCriterion("dips_account_id not between", value1, value2, "dipsAccountId");
            return (Criteria) this;
        }

        public Criteria andDipsAccountNameIsNull() {
            addCriterion("dips_account_name is null");
            return (Criteria) this;
        }

        public Criteria andDipsAccountNameIsNotNull() {
            addCriterion("dips_account_name is not null");
            return (Criteria) this;
        }

        public Criteria andDipsAccountNameEqualTo(String value) {
            addCriterion("dips_account_name =", value, "dipsAccountName");
            return (Criteria) this;
        }

        public Criteria andDipsAccountNameNotEqualTo(String value) {
            addCriterion("dips_account_name <>", value, "dipsAccountName");
            return (Criteria) this;
        }

        public Criteria andDipsAccountNameGreaterThan(String value) {
            addCriterion("dips_account_name >", value, "dipsAccountName");
            return (Criteria) this;
        }

        public Criteria andDipsAccountNameGreaterThanOrEqualTo(String value) {
            addCriterion("dips_account_name >=", value, "dipsAccountName");
            return (Criteria) this;
        }

        public Criteria andDipsAccountNameLessThan(String value) {
            addCriterion("dips_account_name <", value, "dipsAccountName");
            return (Criteria) this;
        }

        public Criteria andDipsAccountNameLessThanOrEqualTo(String value) {
            addCriterion("dips_account_name <=", value, "dipsAccountName");
            return (Criteria) this;
        }

        public Criteria andDipsAccountNameLike(String value) {
            addCriterion("dips_account_name like", value, "dipsAccountName");
            return (Criteria) this;
        }

        public Criteria andDipsAccountNameNotLike(String value) {
            addCriterion("dips_account_name not like", value, "dipsAccountName");
            return (Criteria) this;
        }

        public Criteria andDipsAccountNameIn(List<String> values) {
            addCriterion("dips_account_name in", values, "dipsAccountName");
            return (Criteria) this;
        }

        public Criteria andDipsAccountNameNotIn(List<String> values) {
            addCriterion("dips_account_name not in", values, "dipsAccountName");
            return (Criteria) this;
        }

        public Criteria andDipsAccountNameBetween(String value1, String value2) {
            addCriterion("dips_account_name between", value1, value2, "dipsAccountName");
            return (Criteria) this;
        }

        public Criteria andDipsAccountNameNotBetween(String value1, String value2) {
            addCriterion("dips_account_name not between", value1, value2, "dipsAccountName");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNull() {
            addCriterion("phone_number is null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNotNull() {
            addCriterion("phone_number is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberEqualTo(String value) {
            addCriterion("phone_number =", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotEqualTo(String value) {
            addCriterion("phone_number <>", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThan(String value) {
            addCriterion("phone_number >", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThanOrEqualTo(String value) {
            addCriterion("phone_number >=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThan(String value) {
            addCriterion("phone_number <", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThanOrEqualTo(String value) {
            addCriterion("phone_number <=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLike(String value) {
            addCriterion("phone_number like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotLike(String value) {
            addCriterion("phone_number not like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIn(List<String> values) {
            addCriterion("phone_number in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotIn(List<String> values) {
            addCriterion("phone_number not in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberBetween(String value1, String value2) {
            addCriterion("phone_number between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotBetween(String value1, String value2) {
            addCriterion("phone_number not between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andSwimOperatorIdIsNull() {
            addCriterion("swim_operator_id is null");
            return (Criteria) this;
        }

        public Criteria andSwimOperatorIdIsNotNull() {
            addCriterion("swim_operator_id is not null");
            return (Criteria) this;
        }

        public Criteria andSwimOperatorIdEqualTo(String value) {
            addCriterion("swim_operator_id =", value, "swimOperatorId");
            return (Criteria) this;
        }

        public Criteria andSwimOperatorIdNotEqualTo(String value) {
            addCriterion("swim_operator_id <>", value, "swimOperatorId");
            return (Criteria) this;
        }

        public Criteria andSwimOperatorIdGreaterThan(String value) {
            addCriterion("swim_operator_id >", value, "swimOperatorId");
            return (Criteria) this;
        }

        public Criteria andSwimOperatorIdGreaterThanOrEqualTo(String value) {
            addCriterion("swim_operator_id >=", value, "swimOperatorId");
            return (Criteria) this;
        }

        public Criteria andSwimOperatorIdLessThan(String value) {
            addCriterion("swim_operator_id <", value, "swimOperatorId");
            return (Criteria) this;
        }

        public Criteria andSwimOperatorIdLessThanOrEqualTo(String value) {
            addCriterion("swim_operator_id <=", value, "swimOperatorId");
            return (Criteria) this;
        }

        public Criteria andSwimOperatorIdLike(String value) {
            addCriterion("swim_operator_id like", value, "swimOperatorId");
            return (Criteria) this;
        }

        public Criteria andSwimOperatorIdNotLike(String value) {
            addCriterion("swim_operator_id not like", value, "swimOperatorId");
            return (Criteria) this;
        }

        public Criteria andSwimOperatorIdIn(List<String> values) {
            addCriterion("swim_operator_id in", values, "swimOperatorId");
            return (Criteria) this;
        }

        public Criteria andSwimOperatorIdNotIn(List<String> values) {
            addCriterion("swim_operator_id not in", values, "swimOperatorId");
            return (Criteria) this;
        }

        public Criteria andSwimOperatorIdBetween(String value1, String value2) {
            addCriterion("swim_operator_id between", value1, value2, "swimOperatorId");
            return (Criteria) this;
        }

        public Criteria andSwimOperatorIdNotBetween(String value1, String value2) {
            addCriterion("swim_operator_id not between", value1, value2, "swimOperatorId");
            return (Criteria) this;
        }

        public Criteria andCreationIdIsNull() {
            addCriterion("creation_id is null");
            return (Criteria) this;
        }

        public Criteria andCreationIdIsNotNull() {
            addCriterion("creation_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreationIdEqualTo(String value) {
            addCriterion("creation_id =", value, "creationId");
            return (Criteria) this;
        }

        public Criteria andCreationIdNotEqualTo(String value) {
            addCriterion("creation_id <>", value, "creationId");
            return (Criteria) this;
        }

        public Criteria andCreationIdGreaterThan(String value) {
            addCriterion("creation_id >", value, "creationId");
            return (Criteria) this;
        }

        public Criteria andCreationIdGreaterThanOrEqualTo(String value) {
            addCriterion("creation_id >=", value, "creationId");
            return (Criteria) this;
        }

        public Criteria andCreationIdLessThan(String value) {
            addCriterion("creation_id <", value, "creationId");
            return (Criteria) this;
        }

        public Criteria andCreationIdLessThanOrEqualTo(String value) {
            addCriterion("creation_id <=", value, "creationId");
            return (Criteria) this;
        }

        public Criteria andCreationIdLike(String value) {
            addCriterion("creation_id like", value, "creationId");
            return (Criteria) this;
        }

        public Criteria andCreationIdNotLike(String value) {
            addCriterion("creation_id not like", value, "creationId");
            return (Criteria) this;
        }

        public Criteria andCreationIdIn(List<String> values) {
            addCriterion("creation_id in", values, "creationId");
            return (Criteria) this;
        }

        public Criteria andCreationIdNotIn(List<String> values) {
            addCriterion("creation_id not in", values, "creationId");
            return (Criteria) this;
        }

        public Criteria andCreationIdBetween(String value1, String value2) {
            addCriterion("creation_id between", value1, value2, "creationId");
            return (Criteria) this;
        }

        public Criteria andCreationIdNotBetween(String value1, String value2) {
            addCriterion("creation_id not between", value1, value2, "creationId");
            return (Criteria) this;
        }

        public Criteria andCreationDatetimeIsNull() {
            addCriterion("creation_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreationDatetimeIsNotNull() {
            addCriterion("creation_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreationDatetimeEqualTo(LocalDateTime value) {
            addCriterion("creation_datetime =", value, "creationDatetime");
            return (Criteria) this;
        }

        public Criteria andCreationDatetimeNotEqualTo(LocalDateTime value) {
            addCriterion("creation_datetime <>", value, "creationDatetime");
            return (Criteria) this;
        }

        public Criteria andCreationDatetimeGreaterThan(LocalDateTime value) {
            addCriterion("creation_datetime >", value, "creationDatetime");
            return (Criteria) this;
        }

        public Criteria andCreationDatetimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("creation_datetime >=", value, "creationDatetime");
            return (Criteria) this;
        }

        public Criteria andCreationDatetimeLessThan(LocalDateTime value) {
            addCriterion("creation_datetime <", value, "creationDatetime");
            return (Criteria) this;
        }

        public Criteria andCreationDatetimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("creation_datetime <=", value, "creationDatetime");
            return (Criteria) this;
        }

        public Criteria andCreationDatetimeIn(List<LocalDateTime> values) {
            addCriterion("creation_datetime in", values, "creationDatetime");
            return (Criteria) this;
        }

        public Criteria andCreationDatetimeNotIn(List<LocalDateTime> values) {
            addCriterion("creation_datetime not in", values, "creationDatetime");
            return (Criteria) this;
        }

        public Criteria andCreationDatetimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("creation_datetime between", value1, value2, "creationDatetime");
            return (Criteria) this;
        }

        public Criteria andCreationDatetimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("creation_datetime not between", value1, value2, "creationDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNull() {
            addCriterion("update_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIsNotNull() {
            addCriterion("update_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateIdEqualTo(String value) {
            addCriterion("update_id =", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotEqualTo(String value) {
            addCriterion("update_id <>", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThan(String value) {
            addCriterion("update_id >", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdGreaterThanOrEqualTo(String value) {
            addCriterion("update_id >=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThan(String value) {
            addCriterion("update_id <", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLessThanOrEqualTo(String value) {
            addCriterion("update_id <=", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdLike(String value) {
            addCriterion("update_id like", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotLike(String value) {
            addCriterion("update_id not like", value, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdIn(List<String> values) {
            addCriterion("update_id in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotIn(List<String> values) {
            addCriterion("update_id not in", values, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdBetween(String value1, String value2) {
            addCriterion("update_id between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateIdNotBetween(String value1, String value2) {
            addCriterion("update_id not between", value1, value2, "updateId");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNull() {
            addCriterion("update_datetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNotNull() {
            addCriterion("update_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeEqualTo(LocalDateTime value) {
            addCriterion("update_datetime =", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotEqualTo(LocalDateTime value) {
            addCriterion("update_datetime <>", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThan(LocalDateTime value) {
            addCriterion("update_datetime >", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_datetime >=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThan(LocalDateTime value) {
            addCriterion("update_datetime <", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_datetime <=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIn(List<LocalDateTime> values) {
            addCriterion("update_datetime in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotIn(List<LocalDateTime> values) {
            addCriterion("update_datetime not in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_datetime between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_datetime not between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIsNull() {
            addCriterion("deleted_flag is null");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIsNotNull() {
            addCriterion("deleted_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagEqualTo(Boolean value) {
            addCriterion("deleted_flag =", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotEqualTo(Boolean value) {
            addCriterion("deleted_flag <>", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagGreaterThan(Boolean value) {
            addCriterion("deleted_flag >", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("deleted_flag >=", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagLessThan(Boolean value) {
            addCriterion("deleted_flag <", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("deleted_flag <=", value, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagIn(List<Boolean> values) {
            addCriterion("deleted_flag in", values, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotIn(List<Boolean> values) {
            addCriterion("deleted_flag not in", values, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted_flag between", value1, value2, "deletedFlag");
            return (Criteria) this;
        }

        public Criteria andDeletedFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("deleted_flag not between", value1, value2, "deletedFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table operator_attribute
     *
     * @mbg.generated do_not_delete_during_merge Mon Feb 02 11:23:32 JST 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table operator_attribute
     *
     * @mbg.generated Mon Feb 02 11:23:32 JST 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}