package jp.go.meti.drone.user_attr.repository.entity;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class UserAttributeEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attribute.user_id
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attribute.mail_address
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    private String mailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attribute.user_name
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attribute.role
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attribute.operator_id
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    private String operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attribute.creation_id
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    private String creationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attribute.creation_datetime
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    private LocalDateTime creationDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attribute.update_id
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    private String updateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attribute.update_datetime
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    private LocalDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_attribute.deleted_flag
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    private Boolean deletedFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_attribute
     *
     * @mbg.generated Fri Dec 19 14:33:31 JST 2025
     */
    private static final long serialVersionUID = 1L;
}